# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TodoWithMonitorSampleApp' do
  use_frameworks!
  pod "Suas", :path => "../../"
  pod "SuasMonitorMiddleware", :path => "../../../SuasMonitorMiddleware"
end
