# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TodoSampleApp-iOS' do
  use_frameworks!
  pod "Suas", :path => "../../"
end

target 'TodoSampleApp-Mac' do
  use_frameworks!
  pod "Suas", :path => "../../"
end
